# Generated by Django 5.0.6 on 2024-06-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitiesmaster',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='entitiesmaster',
            old_name='Time',
            new_name='time',
        ),
    ]
