# Generated by Django 5.0.6 on 2024-06-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_date_entitiesmaster_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='entitiesmaster',
            name='artist_name',
        ),
        migrations.RemoveField(
            model_name='entitiesmaster',
            name='artist_role',
        ),
        migrations.RemoveField(
            model_name='entitiesmaster',
            name='program_name',
        ),
        migrations.AddField(
            model_name='entitiesmaster',
            name='artists',
            field=models.ManyToManyField(to='api.artists'),
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artists')),
            ],
        ),
        migrations.AddField(
            model_name='entitiesmaster',
            name='programs',
            field=models.ManyToManyField(to='api.programs'),
        ),
    ]
