# Generated by Django 5.0.6 on 2024-06-21 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_artists_remove_entitiesmaster_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='artists',
            unique_together={('name', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='programs',
            unique_together={('name', 'artists')},
        ),
    ]
