# Generated by Django 5.0.6 on 2024-06-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_artists_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='artists',
            field=models.CharField(max_length=100),
        ),
    ]
