# Generated by Django 5.0.6 on 2024-06-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_programs_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitiesmaster',
            name='date',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='entitiesmaster',
            name='time',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
