# Generated by Django 5.0.6 on 2024-06-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_entitiesmaster_date_alter_entitiesmaster_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitiesmaster',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
