# Generated by Django 5.0.6 on 2024-06-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_entitiesmaster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitiesmaster',
            name='artists',
            field=models.ManyToManyField(blank=True, null=True, to='api.artists'),
        ),
        migrations.AlterField(
            model_name='entitiesmaster',
            name='programs',
            field=models.ManyToManyField(blank=True, null=True, to='api.programs'),
        ),
    ]
