# Generated by Django 5.0.6 on 2024-06-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_entitiesmaster_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitiesmaster',
            name='artists',
            field=models.ManyToManyField(blank=True, to='api.artists'),
        ),
        migrations.AlterField(
            model_name='entitiesmaster',
            name='programs',
            field=models.ManyToManyField(blank=True, to='api.programs'),
        ),
    ]
